[2023-11-23T00:31:03.448+0000] {processor.py:157} INFO - Started process (PID=172) to work on /opt/airflow/dags/drags.py
[2023-11-23T00:31:03.450+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/drags.py for tasks to queue
[2023-11-23T00:31:03.451+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:31:03.451+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/drags.py
[2023-11-23T00:31:03.499+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:31:03.493+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/drags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/drags.py", line 3, in <module>
    from airflow.operators.sensors import ExternalTaskSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-11-23T00:31:03.502+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/drags.py
[2023-11-23T00:31:03.534+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/drags.py took 0.091 seconds
[2023-11-23T00:31:33.867+0000] {processor.py:157} INFO - Started process (PID=189) to work on /opt/airflow/dags/drags.py
[2023-11-23T00:31:33.869+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/drags.py for tasks to queue
[2023-11-23T00:31:33.871+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:31:33.871+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/drags.py
[2023-11-23T00:31:33.899+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:31:33.897+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/drags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/drags.py", line 3, in <module>
    from airflow.operators.sensors import ExternalTaskSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-11-23T00:31:33.900+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/drags.py
[2023-11-23T00:31:33.963+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/drags.py took 0.102 seconds
[2023-11-23T00:32:04.428+0000] {processor.py:157} INFO - Started process (PID=206) to work on /opt/airflow/dags/drags.py
[2023-11-23T00:32:04.431+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/drags.py for tasks to queue
[2023-11-23T00:32:04.432+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:32:04.432+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/drags.py
[2023-11-23T00:32:04.451+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:32:04.447+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/drags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/drags.py", line 3, in <module>
    from airflow.operators.sensors import ExternalTaskSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-11-23T00:32:04.452+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/drags.py
[2023-11-23T00:32:04.470+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/drags.py took 0.045 seconds
[2023-11-23T00:32:34.806+0000] {processor.py:157} INFO - Started process (PID=228) to work on /opt/airflow/dags/drags.py
[2023-11-23T00:32:34.808+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/drags.py for tasks to queue
[2023-11-23T00:32:34.809+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:32:34.809+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/drags.py
[2023-11-23T00:32:34.858+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:32:34.852+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/drags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/drags.py", line 3, in <module>
    from airflow.operators.sensors import ExternalTaskSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-11-23T00:32:34.860+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/drags.py
[2023-11-23T00:32:34.886+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/drags.py took 0.085 seconds
[2023-11-23T00:33:05.283+0000] {processor.py:157} INFO - Started process (PID=253) to work on /opt/airflow/dags/drags.py
[2023-11-23T00:33:05.286+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/drags.py for tasks to queue
[2023-11-23T00:33:05.288+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:33:05.287+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/drags.py
[2023-11-23T00:33:05.330+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:33:05.323+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/drags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/drags.py", line 3, in <module>
    from airflow.operators.sensors import ExternalTaskSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-11-23T00:33:05.333+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/drags.py
[2023-11-23T00:33:05.404+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/drags.py took 0.127 seconds
[2023-11-23T00:33:36.203+0000] {processor.py:157} INFO - Started process (PID=272) to work on /opt/airflow/dags/drags.py
[2023-11-23T00:33:36.205+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/drags.py for tasks to queue
[2023-11-23T00:33:36.206+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:33:36.206+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/drags.py
[2023-11-23T00:33:36.228+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:33:36.223+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/drags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/drags.py", line 3, in <module>
    from airflow.operators.sensors import ExternalTaskSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-11-23T00:33:36.229+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/drags.py
[2023-11-23T00:33:36.257+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/drags.py took 0.058 seconds
[2023-11-23T00:34:08.123+0000] {processor.py:157} INFO - Started process (PID=289) to work on /opt/airflow/dags/drags.py
[2023-11-23T00:34:08.125+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/drags.py for tasks to queue
[2023-11-23T00:34:08.127+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:34:08.127+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/drags.py
[2023-11-23T00:34:08.155+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:34:08.151+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/drags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/drags.py", line 3, in <module>
    from airflow.operators.sensors import ExternalTaskSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-11-23T00:34:08.157+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/drags.py
[2023-11-23T00:34:08.183+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/drags.py took 1.495 seconds
[2023-11-23T00:34:38.244+0000] {processor.py:157} INFO - Started process (PID=317) to work on /opt/airflow/dags/drags.py
[2023-11-23T00:34:38.245+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/drags.py for tasks to queue
[2023-11-23T00:34:38.247+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:34:38.246+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/drags.py
[2023-11-23T00:34:38.265+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:34:38.261+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/drags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/drags.py", line 3, in <module>
    from airflow.operators.sensors import ExternalTaskSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-11-23T00:34:38.267+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/drags.py
[2023-11-23T00:34:41.066+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/drags.py took 2.826 seconds
[2023-11-23T00:35:11.449+0000] {processor.py:157} INFO - Started process (PID=335) to work on /opt/airflow/dags/drags.py
[2023-11-23T00:35:11.452+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/drags.py for tasks to queue
[2023-11-23T00:35:11.455+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:35:11.454+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/drags.py
[2023-11-23T00:35:11.490+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:35:11.482+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/drags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/drags.py", line 3, in <module>
    from airflow.operators.sensors import ExternalTaskSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-11-23T00:35:11.492+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/drags.py
[2023-11-23T00:35:11.527+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/drags.py took 0.084 seconds
[2023-11-23T00:35:41.836+0000] {processor.py:157} INFO - Started process (PID=352) to work on /opt/airflow/dags/drags.py
[2023-11-23T00:35:41.838+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/drags.py for tasks to queue
[2023-11-23T00:35:41.840+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:35:41.839+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/drags.py
[2023-11-23T00:35:41.870+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:35:41.863+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/drags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/drags.py", line 3, in <module>
    from airflow.operators.sensors import ExternalTaskSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-11-23T00:35:41.872+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/drags.py
[2023-11-23T00:35:41.905+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/drags.py took 0.077 seconds
[2023-11-23T00:36:22.401+0000] {processor.py:157} INFO - Started process (PID=365) to work on /opt/airflow/dags/drags.py
[2023-11-23T00:36:22.403+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/drags.py for tasks to queue
[2023-11-23T00:36:22.405+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:36:22.404+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/drags.py
[2023-11-23T00:36:22.430+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:36:22.426+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/drags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/drags.py", line 3, in <module>
    from airflow.operators.sensors import ExternalTaskSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-11-23T00:36:22.432+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/drags.py
[2023-11-23T00:36:22.465+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/drags.py took 0.069 seconds
[2023-11-23T00:36:52.852+0000] {processor.py:157} INFO - Started process (PID=381) to work on /opt/airflow/dags/drags.py
[2023-11-23T00:36:52.859+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/drags.py for tasks to queue
[2023-11-23T00:36:52.860+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:36:52.860+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/drags.py
[2023-11-23T00:36:52.884+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:36:52.881+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/drags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/drags.py", line 3, in <module>
    from airflow.operators.sensors import ExternalTaskSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-11-23T00:36:52.886+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/drags.py
[2023-11-23T00:36:52.912+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/drags.py took 0.063 seconds
[2023-11-23T00:37:23.291+0000] {processor.py:157} INFO - Started process (PID=398) to work on /opt/airflow/dags/drags.py
[2023-11-23T00:37:23.293+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/drags.py for tasks to queue
[2023-11-23T00:37:23.295+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:37:23.294+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/drags.py
[2023-11-23T00:37:23.319+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:37:23.314+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/drags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/drags.py", line 3, in <module>
    from airflow.operators.sensors import ExternalTaskSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-11-23T00:37:23.321+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/drags.py
[2023-11-23T00:37:23.358+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/drags.py took 0.072 seconds
[2023-11-23T00:37:53.676+0000] {processor.py:157} INFO - Started process (PID=415) to work on /opt/airflow/dags/drags.py
[2023-11-23T00:37:53.677+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/drags.py for tasks to queue
[2023-11-23T00:37:53.678+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:37:53.678+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/drags.py
[2023-11-23T00:37:53.698+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:37:53.694+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/drags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/drags.py", line 3, in <module>
    from airflow.operators.sensors import ExternalTaskSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-11-23T00:37:53.699+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/drags.py
[2023-11-23T00:37:53.728+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/drags.py took 0.057 seconds
[2023-11-23T00:38:24.034+0000] {processor.py:157} INFO - Started process (PID=432) to work on /opt/airflow/dags/drags.py
[2023-11-23T00:38:24.035+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/drags.py for tasks to queue
[2023-11-23T00:38:24.036+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:38:24.036+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/drags.py
[2023-11-23T00:38:24.054+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:38:24.050+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/drags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/drags.py", line 3, in <module>
    from airflow.operators.sensors import ExternalTaskSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-11-23T00:38:24.055+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/drags.py
[2023-11-23T00:38:24.082+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/drags.py took 0.053 seconds
[2023-11-23T00:38:54.441+0000] {processor.py:157} INFO - Started process (PID=449) to work on /opt/airflow/dags/drags.py
[2023-11-23T00:38:54.443+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/drags.py for tasks to queue
[2023-11-23T00:38:54.444+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:38:54.443+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/drags.py
[2023-11-23T00:38:54.468+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:38:54.464+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/drags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/drags.py", line 3, in <module>
    from airflow.operators.sensors import ExternalTaskSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-11-23T00:38:54.469+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/drags.py
[2023-11-23T00:38:54.490+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/drags.py took 0.051 seconds
[2023-11-23T00:39:24.942+0000] {processor.py:157} INFO - Started process (PID=466) to work on /opt/airflow/dags/drags.py
[2023-11-23T00:39:24.944+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/drags.py for tasks to queue
[2023-11-23T00:39:24.945+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:39:24.945+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/drags.py
[2023-11-23T00:39:24.966+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:39:24.963+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/drags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/drags.py", line 3, in <module>
    from airflow.operators.sensors import ExternalTaskSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-11-23T00:39:24.967+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/drags.py
[2023-11-23T00:39:24.991+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/drags.py took 0.053 seconds
[2023-11-23T00:39:55.492+0000] {processor.py:157} INFO - Started process (PID=483) to work on /opt/airflow/dags/drags.py
[2023-11-23T00:39:55.494+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/drags.py for tasks to queue
[2023-11-23T00:39:55.496+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:39:55.495+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/drags.py
[2023-11-23T00:39:55.531+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:39:55.526+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/drags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/drags.py", line 3, in <module>
    from airflow.operators.sensors import ExternalTaskSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-11-23T00:39:55.532+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/drags.py
[2023-11-23T00:39:55.597+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/drags.py took 0.113 seconds
[2023-11-23T00:40:26.038+0000] {processor.py:157} INFO - Started process (PID=500) to work on /opt/airflow/dags/drags.py
[2023-11-23T00:40:26.039+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/drags.py for tasks to queue
[2023-11-23T00:40:26.040+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:40:26.040+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/drags.py
[2023-11-23T00:40:26.057+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:40:26.054+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/drags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/drags.py", line 3, in <module>
    from airflow.operators.sensors import ExternalTaskSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-11-23T00:40:26.058+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/drags.py
[2023-11-23T00:40:26.076+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/drags.py took 0.041 seconds
[2023-11-23T00:40:56.568+0000] {processor.py:157} INFO - Started process (PID=517) to work on /opt/airflow/dags/drags.py
[2023-11-23T00:40:56.570+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/drags.py for tasks to queue
[2023-11-23T00:40:56.571+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:40:56.570+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/drags.py
[2023-11-23T00:40:56.586+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:40:56.583+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/drags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/drags.py", line 3, in <module>
    from airflow.operators.sensors import ExternalTaskSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-11-23T00:40:56.587+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/drags.py
[2023-11-23T00:40:56.650+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/drags.py took 0.086 seconds
[2023-11-23T00:41:27.295+0000] {processor.py:157} INFO - Started process (PID=534) to work on /opt/airflow/dags/drags.py
[2023-11-23T00:41:27.297+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/drags.py for tasks to queue
[2023-11-23T00:41:27.298+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:41:27.298+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/drags.py
[2023-11-23T00:41:27.321+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:41:27.318+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/drags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/drags.py", line 3, in <module>
    from airflow.operators.sensors import ExternalTaskSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-11-23T00:41:27.322+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/drags.py
[2023-11-23T00:41:27.386+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/drags.py took 0.094 seconds
[2023-11-23T00:41:57.795+0000] {processor.py:157} INFO - Started process (PID=551) to work on /opt/airflow/dags/drags.py
[2023-11-23T00:41:57.797+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/drags.py for tasks to queue
[2023-11-23T00:41:57.800+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:41:57.799+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/drags.py
[2023-11-23T00:41:57.848+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:41:57.843+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/drags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/drags.py", line 3, in <module>
    from airflow.operators.sensors import ExternalTaskSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-11-23T00:41:57.851+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/drags.py
[2023-11-23T00:41:57.924+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/drags.py took 0.136 seconds
[2023-11-23T00:42:28.440+0000] {processor.py:157} INFO - Started process (PID=568) to work on /opt/airflow/dags/drags.py
[2023-11-23T00:42:28.441+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/drags.py for tasks to queue
[2023-11-23T00:42:28.442+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:42:28.442+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/drags.py
[2023-11-23T00:42:28.460+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:42:28.458+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/drags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/drags.py", line 3, in <module>
    from airflow.operators.sensors import ExternalTaskSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-11-23T00:42:28.462+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/drags.py
[2023-11-23T00:42:28.485+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/drags.py took 0.049 seconds
[2023-11-23T00:42:58.954+0000] {processor.py:157} INFO - Started process (PID=585) to work on /opt/airflow/dags/drags.py
[2023-11-23T00:42:58.955+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/drags.py for tasks to queue
[2023-11-23T00:42:58.957+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:42:58.956+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/drags.py
[2023-11-23T00:42:58.978+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:42:58.974+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/drags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/drags.py", line 3, in <module>
    from airflow.operators.sensors import ExternalTaskSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-11-23T00:42:58.980+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/drags.py
[2023-11-23T00:42:59.046+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/drags.py took 0.097 seconds
[2023-11-23T00:43:29.543+0000] {processor.py:157} INFO - Started process (PID=602) to work on /opt/airflow/dags/drags.py
[2023-11-23T00:43:29.545+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/drags.py for tasks to queue
[2023-11-23T00:43:29.547+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:43:29.547+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/drags.py
[2023-11-23T00:43:29.581+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:43:29.575+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/drags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/drags.py", line 3, in <module>
    from airflow.operators.sensors import ExternalTaskSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-11-23T00:43:29.582+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/drags.py
[2023-11-23T00:43:29.616+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/drags.py took 0.079 seconds
[2023-11-23T00:44:00.117+0000] {processor.py:157} INFO - Started process (PID=619) to work on /opt/airflow/dags/drags.py
[2023-11-23T00:44:00.118+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/drags.py for tasks to queue
[2023-11-23T00:44:00.119+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:44:00.118+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/drags.py
[2023-11-23T00:44:00.135+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:44:00.132+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/drags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/drags.py", line 3, in <module>
    from airflow.operators.sensors import ExternalTaskSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-11-23T00:44:00.136+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/drags.py
[2023-11-23T00:44:00.199+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/drags.py took 0.089 seconds
[2023-11-23T00:44:30.723+0000] {processor.py:157} INFO - Started process (PID=636) to work on /opt/airflow/dags/drags.py
[2023-11-23T00:44:30.725+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/drags.py for tasks to queue
[2023-11-23T00:44:30.727+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:44:30.727+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/drags.py
[2023-11-23T00:44:30.776+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:44:30.767+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/drags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/drags.py", line 3, in <module>
    from airflow.operators.sensors import ExternalTaskSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-11-23T00:44:30.777+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/drags.py
[2023-11-23T00:44:30.848+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/drags.py took 0.132 seconds
[2023-11-23T00:45:01.317+0000] {processor.py:157} INFO - Started process (PID=653) to work on /opt/airflow/dags/drags.py
[2023-11-23T00:45:01.319+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/drags.py for tasks to queue
[2023-11-23T00:45:01.322+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:45:01.321+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/drags.py
[2023-11-23T00:45:01.378+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:45:01.366+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/drags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/drags.py", line 3, in <module>
    from airflow.operators.sensors import ExternalTaskSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-11-23T00:45:01.382+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/drags.py
[2023-11-23T00:45:01.427+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/drags.py took 0.119 seconds
[2023-11-23T00:45:31.892+0000] {processor.py:157} INFO - Started process (PID=670) to work on /opt/airflow/dags/drags.py
[2023-11-23T00:45:31.894+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/drags.py for tasks to queue
[2023-11-23T00:45:31.896+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:45:31.895+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/drags.py
[2023-11-23T00:45:31.923+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:45:31.918+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/drags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/drags.py", line 3, in <module>
    from airflow.operators.sensors import ExternalTaskSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-11-23T00:45:31.924+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/drags.py
[2023-11-23T00:45:31.992+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/drags.py took 0.104 seconds
[2023-11-23T00:46:02.510+0000] {processor.py:157} INFO - Started process (PID=687) to work on /opt/airflow/dags/drags.py
[2023-11-23T00:46:02.512+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/drags.py for tasks to queue
[2023-11-23T00:46:02.515+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:46:02.514+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/drags.py
[2023-11-23T00:46:02.564+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:46:02.554+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/drags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/drags.py", line 3, in <module>
    from airflow.operators.sensors import ExternalTaskSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-11-23T00:46:02.568+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/drags.py
[2023-11-23T00:46:02.594+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/drags.py took 0.094 seconds
[2023-11-23T00:46:33.111+0000] {processor.py:157} INFO - Started process (PID=704) to work on /opt/airflow/dags/drags.py
[2023-11-23T00:46:33.113+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/drags.py for tasks to queue
[2023-11-23T00:46:33.115+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:46:33.115+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/drags.py
[2023-11-23T00:46:33.163+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:46:33.155+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/drags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/drags.py", line 3, in <module>
    from airflow.operators.sensors import ExternalTaskSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-11-23T00:46:33.165+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/drags.py
[2023-11-23T00:46:33.240+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/drags.py took 0.137 seconds
[2023-11-23T00:47:03.627+0000] {processor.py:157} INFO - Started process (PID=721) to work on /opt/airflow/dags/drags.py
[2023-11-23T00:47:03.629+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/drags.py for tasks to queue
[2023-11-23T00:47:03.631+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:47:03.630+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/drags.py
[2023-11-23T00:47:03.654+0000] {logging_mixin.py:151} INFO - [2023-11-23T00:47:03.650+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/drags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/drags.py", line 3, in <module>
    from airflow.operators.sensors import ExternalTaskSensor
ModuleNotFoundError: No module named 'airflow.operators.sensors'
[2023-11-23T00:47:03.656+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/drags.py
[2023-11-23T00:47:03.675+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/drags.py took 0.051 seconds
